### ISSUE TITLE
テスト

### ISSUE THREAD

**Issue by yuto-kimura-g** [Sakoda2269/white_space_transcompiler#1]
今後更に拡張するつもりなら，テストを書いた方が良さそうだな～と思いました

`unittest`
  - https://docs.python.org/3/library/unittest.html
  - 標準ライブラリ
  - Classを作って良い感じにやる

`pytest`
  - https://docs.pytest.org/en/stable/contents.html
  - `tests/`でassertを入れて`pytest`するだけ．とりあえず動かすならこっちの方が簡単

とかを使ってみてもいいんじゃないでしょうか

**Comment by Sakoda2269** [comment]
テストをするのはいい考えなのですが、pythonのテストでテストできそうなところは入力されたプログラムを解析するところだけになりそうな感じです。(そしてここはほぼ変わらないと思う)　

実行するのはWhitespaceになるので、コンパイル前のプログラムと結果を用意して自動テストをしてくれるバッチを書くのがいいかもしれません。

**Comment by yuto-kimura-g** [comment]
なるほど．
なら，入力されたプログラムを解析する処理が意図せず変わっていないことを保証するために多少テスト入れておく感じかな．

バッチ書くなら，Makefile使ってみても良いかもしれない
ちょっと前に入門したんだけど，便利だよ
